[workspace]
resolver = "2"
members = [
    "src/core",
    "src/consensus",
    "src/network",
    "src/wallet",
    "src/miner",
    "src/node",
]


[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true
